language: python
python:
  - 3.6
sudo: false
install:
  - pip install -r requirements.txt
  - pip install pytest
script:
  - py.test src/mypackage_core
  - py.test src/mypackage_theme
  - make checkout
